<?php

/*
|--------------------------------------------------------------------------
| Simulation Roles
|--------------------------------------------------------------------------
|
| Profession → archetype mapping, recipes per profession, starting wealth
| per archetype. Drives the per-archetype action loops in Ticker.
|
| Five archetypes:
|   household_producer — farms/gardens, eats own food, sells surplus
|   market_craftsman   — makes goods at workshop, sells for coin, buys food
|   service_provider   — serves clients at workplace (same produce/sell loop
|                        but with consumables), buys food
|   rent_extractor     — collects tribute from nearby NPCs, buys food
|   dependent          — begs for coin from nearby NPCs, buys food
|
*/

return [

    'archetype_for_profession' => [
        'farmer' => 'household_producer',
        'shepherd' => 'household_producer',
        'goatherd' => 'household_producer',
        'fisher' => 'household_producer',
        'hunter' => 'household_producer',
        'trapper' => 'household_producer',
        'forager' => 'household_producer',
        'miller' => 'household_producer',

        'blacksmith' => 'market_craftsman',
        'weaver' => 'market_craftsman',
        'tailor' => 'market_craftsman',
        'cobbler' => 'market_craftsman',
        'tanner' => 'market_craftsman',
        'carpenter' => 'market_craftsman',
        'mason' => 'market_craftsman',
        'cooper' => 'market_craftsman',
        'fletcher' => 'market_craftsman',
        'bowyer' => 'market_craftsman',
        'potter' => 'market_craftsman',
        'baker' => 'market_craftsman',
        'butcher' => 'market_craftsman',
        'brewer' => 'market_craftsman',

        'innkeeper' => 'service_provider',
        'barkeep' => 'service_provider',
        'cook' => 'service_provider',
        'alchemist' => 'service_provider',
        'herbalist' => 'service_provider',
        'healer' => 'service_provider',
        'midwife' => 'service_provider',
        'gravedigger' => 'service_provider',
        'scribe' => 'service_provider',

        'priest' => 'rent_extractor',
        'acolyte' => 'rent_extractor',
        'guard' => 'rent_extractor',
        'soldier' => 'rent_extractor',
        'noble' => 'rent_extractor',
        'steward' => 'rent_extractor',
        'mayor' => 'rent_extractor',
        'constable' => 'rent_extractor',
        'tax_collector' => 'rent_extractor',

        'beggar' => 'dependent',
        'rat_catcher' => 'dependent',
        'nightsoil_collector' => 'dependent',
        'minstrel' => 'dependent',
        'jester' => 'dependent',
        'cutpurse' => 'dependent',
        'thief' => 'dependent',
    ],

    // per-profession production recipe — what they make when working
    'recipes' => [
        'farmer' => [
            'name' => 'turnip',
            'type' => 'food',
            'subtype' => 'turnip',
            'material' => 'flesh',
            'affordances' => ['hunger' => 30],
            'price' => 2,
            'max_stock' => 6,
            'weight' => 1,
            'value' => 2,
        ],
        'shepherd' => [
            'name' => 'wool bundle',
            'type' => 'material',
            'subtype' => 'wool',
            'material' => 'wool',
            'affordances' => ['hygiene' => 15],
            'price' => 4,
            'max_stock' => 4,
            'weight' => 2,
            'value' => 4,
        ],
        'fisher' => [
            'name' => 'fresh fish',
            'type' => 'food',
            'subtype' => 'fish',
            'material' => 'flesh',
            'affordances' => ['hunger' => 40],
            'price' => 3,
            'max_stock' => 5,
            'weight' => 1,
            'value' => 3,
        ],
        'hunter' => [
            'name' => 'venison cut',
            'type' => 'food',
            'subtype' => 'meat',
            'material' => 'flesh',
            'affordances' => ['hunger' => 55],
            'price' => 6,
            'max_stock' => 3,
            'weight' => 2,
            'value' => 6,
        ],
        'miller' => [
            'name' => 'flour sack',
            'type' => 'food',
            'subtype' => 'flour',
            'material' => 'grain',
            'affordances' => ['hunger' => 15],
            'price' => 3,
            'max_stock' => 4,
            'weight' => 3,
            'value' => 3,
        ],

        'blacksmith' => [
            'name' => 'iron sword',
            'type' => 'weapon',
            'subtype' => 'shortsword',
            'material' => 'iron',
            'affordances' => ['safety' => 30],
            'price' => 25,
            'max_stock' => 2,
            'weight' => 3,
            'value' => 25,
        ],
        'weaver' => [
            'name' => 'linen cloth',
            'type' => 'clothing',
            'subtype' => 'cloth',
            'material' => 'linen',
            'affordances' => ['hygiene' => 20],
            'price' => 8,
            'max_stock' => 3,
            'weight' => 1,
            'value' => 8,
        ],
        'cobbler' => [
            'name' => 'leather boots',
            'type' => 'clothing',
            'subtype' => 'boots',
            'material' => 'leather',
            'affordances' => ['hygiene' => 10],
            'price' => 10,
            'max_stock' => 2,
            'weight' => 1,
            'value' => 10,
        ],
        'tanner' => [
            'name' => 'tanned hide',
            'type' => 'armor',
            'subtype' => 'hide',
            'material' => 'leather',
            'affordances' => ['safety' => 15],
            'price' => 6,
            'max_stock' => 3,
            'weight' => 2,
            'value' => 6,
        ],
        'carpenter' => [
            'name' => 'oak plank',
            'type' => 'tool',
            'subtype' => 'plank',
            'material' => 'oak',
            'affordances' => ['safety' => 8],
            'price' => 4,
            'max_stock' => 4,
            'weight' => 3,
            'value' => 4,
        ],
        'potter' => [
            'name' => 'clay pot',
            'type' => 'tool',
            'subtype' => 'jar',
            'material' => 'clay',
            'affordances' => ['purpose' => 10],
            'price' => 3,
            'max_stock' => 4,
            'weight' => 2,
            'value' => 3,
        ],
        'baker' => [
            'name' => 'bread loaf',
            'type' => 'food',
            'subtype' => 'loaf',
            'material' => 'flesh',
            'affordances' => ['hunger' => 45],
            'price' => 4,
            'max_stock' => 5,
            'weight' => 1,
            'value' => 4,
        ],
        'butcher' => [
            'name' => 'cut of meat',
            'type' => 'food',
            'subtype' => 'meat',
            'material' => 'flesh',
            'affordances' => ['hunger' => 55],
            'price' => 6,
            'max_stock' => 4,
            'weight' => 2,
            'value' => 6,
        ],
        'brewer' => [
            'name' => 'ale cask',
            'type' => 'drink',
            'subtype' => 'ale',
            'material' => 'wood',
            'affordances' => ['thirst' => 40, 'social_need' => 10],
            'price' => 5,
            'max_stock' => 4,
            'weight' => 3,
            'value' => 5,
        ],

        'innkeeper' => [
            'name' => 'pot of stew',
            'type' => 'food',
            'subtype' => 'stew',
            'material' => 'flesh',
            'affordances' => ['hunger' => 50, 'social_need' => 10],
            'price' => 5,
            'max_stock' => 3,
            'weight' => 2,
            'value' => 5,
        ],
        'cook' => [
            'name' => 'meat pie',
            'type' => 'food',
            'subtype' => 'pie',
            'material' => 'flesh',
            'affordances' => ['hunger' => 50],
            'price' => 5,
            'max_stock' => 3,
            'weight' => 1,
            'value' => 5,
        ],
        'alchemist' => [
            'name' => 'healing salve',
            'type' => 'consumable',
            'subtype' => 'salve',
            'material' => 'glass',
            'affordances' => ['hygiene' => 30, 'safety' => 15],
            'price' => 7,
            'max_stock' => 3,
            'weight' => 1,
            'value' => 7,
        ],
        'herbalist' => [
            'name' => 'herb bundle',
            'type' => 'consumable',
            'subtype' => 'poultice',
            'material' => 'flesh',
            'affordances' => ['hygiene' => 20],
            'price' => 4,
            'max_stock' => 3,
            'weight' => 1,
            'value' => 4,
        ],
        'gravedigger' => [
            'name' => 'grave marker',
            'type' => 'furniture',
            'subtype' => 'candle',
            'material' => 'wood',
            'affordances' => ['safety' => 5],
            'price' => 3,
            'max_stock' => 2,
            'weight' => 4,
            'value' => 3,
        ],
        'scribe' => [
            'name' => 'parchment letter',
            'type' => 'tool',
            'subtype' => 'letter',
            'material' => 'paper',
            'affordances' => ['purpose' => 15, 'social_need' => 10],
            'price' => 6,
            'max_stock' => 3,
            'weight' => 1,
            'value' => 6,
        ],
    ],

    'starting_wealth' => [
        'household_producer' => 4,
        'market_craftsman' => 40,
        'service_provider' => 30,
        'rent_extractor' => 150,
        'dependent' => 1,
    ],

    // tribute interval (ticks) and amount per nearby victim
    'rent_extractor' => [
        'tribute_interval' => 4,
        'tribute_amount' => 2,
        'tribute_radius' => 6,
        'min_victim_wealth' => 5,
    ],

    // dependents beg every tick from nearest wealthy within radius
    'dependent' => [
        'beg_radius' => 5,
        'min_donor_wealth' => 15,
        'beg_amount' => 1,
    ],
];
